[
  ./config/console.nix
  ./config/fonts/fontconfig.nix
  ./config/fonts/fontdir.nix
  ./config/fonts/packages.nix
  ./config/i18n.nix
  ./config/iproute2.nix
  ./config/ldap.nix
  ./config/ldso.nix
  ./config/locale.nix
  ./config/mysql.nix
  ./config/networking.nix
  ./config/nix-channel.nix
  ./config/nix-flakes.nix
  ./config/nix-remote-build.nix
  ./config/nix.nix
  ./config/nsswitch.nix
  ./config/power-management.nix
  ./config/qt.nix
  ./config/resolvconf.nix
  ./config/shells-environment.nix
  ./config/stub-ld.nix
  ./config/swap.nix
  ./config/sysctl.nix
  ./config/sysfs.nix
  ./config/system-environment.nix
  ./config/system-path.nix
  ./config/users-groups.nix
  ./config/vte.nix
  ./config/xdg/autostart.nix
  ./config/xdg/icons.nix
  ./config/xdg/menus.nix
  ./config/xdg/mime.nix
  ./config/xdg/portal.nix
  ./config/xdg/portals/wlr.nix
  ./config/zram.nix
  ./hardware/all-firmware.nix
  ./hardware/all-hardware.nix
  ./hardware/cpu/amd-microcode.nix
  ./hardware/cpu/intel-microcode.nix
  ./hardware/cpu/x86-msr.nix
  ./hardware/device-tree.nix
  ./hardware/facter
  ./hardware/graphics.nix
  ./hardware/i2c.nix
  ./hardware/keyboard/qmk.nix
  ./hardware/network/ath-user-regd.nix
  ./hardware/network/b43.nix
  ./hardware/network/intel-2200bg.nix
  ./hardware/printers.nix
  ./hardware/sensor/iio.nix
  ./hardware/steam-hardware.nix
  ./hardware/uinput.nix
  ./hardware/usb-modeswitch.nix
  ./hardware/video/nvidia.nix
  ./hardware/video/switcheroo-control.nix
  ./hardware/video/uvcvideo/default.nix
  ./hardware/video/webcam/ipu6.nix
  ./i18n/input-method/default.nix
  ./installer/tools/tools.nix
  ./misc/assertions.nix
  ./misc/documentation.nix
  ./misc/extra-arguments.nix
  ./misc/ids.nix
  ./misc/lib.nix
  ./misc/locate.nix
  ./misc/meta.nix
  ./misc/nixpkgs-flake.nix
  ./misc/nixpkgs.nix
  ./misc/version.nix
  ./misc/wordlist.nix
  ./programs/bash/bash-completion.nix
  ./programs/bash/bash.nix
  ./programs/bash/ls-colors.nix
  ./programs/chromium.nix
  ./programs/dconf.nix
  ./programs/environment.nix
  ./programs/evince.nix
  ./programs/feedbackd.nix
  ./programs/firefox.nix
  ./programs/firejail.nix
  ./programs/fuse.nix
  ./programs/gamemode.nix
  ./programs/gamescope.nix
  ./programs/gdk-pixbuf.nix
  ./programs/git.nix
  ./programs/gnome-disks.nix
  ./programs/gnome-terminal.nix
  ./programs/gnupg.nix
  ./programs/i3lock.nix
  ./programs/kde-pim.nix
  ./programs/kdeconnect.nix
  ./programs/less.nix
  ./programs/mosh.nix
  ./programs/mtr.nix
  ./programs/nano.nix
  ./programs/neovim.nix
  ./programs/nh.nix
  ./programs/nix-ld.nix
  ./programs/nm-applet.nix
  ./programs/partition-manager.nix
  ./programs/seahorse.nix
  ./programs/shadow.nix
  ./programs/ssh.nix
  ./programs/steam.nix
  ./programs/system-config-printer.nix
  ./programs/thunar.nix
  ./programs/tmux.nix
  ./programs/wayland/gtklock.nix
  ./programs/wayland/hyprland.nix
  ./programs/wayland/labwc.nix
  ./programs/wayland/uwsm.nix
  ./programs/wayland/wayfire.nix
  ./programs/xfconf.nix
  ./programs/xwayland.nix
  ./programs/zsh/oh-my-zsh.nix
  ./programs/zsh/zsh.nix
  ./rename.nix
  ./security/apparmor.nix
  ./security/audit.nix
  ./security/ca.nix
  ./security/default.nix
  ./security/krb5
  ./security/lock-kernel-modules.nix
  ./security/misc.nix
  ./security/oath.nix
  ./security/pam.nix
  ./security/pam_mount.nix
  ./security/polkit.nix
  ./security/rtkit.nix
  ./security/run0.nix
  ./security/sudo-rs.nix
  ./security/sudo.nix
  ./security/tpm2.nix
  ./security/wrappers/default.nix
  ./services/accessibility/speechd.nix
  ./services/audio/alsa.nix
  ./services/audio/jack.nix
  ./services/audio/mpd.nix
  ./services/audio/pulseaudio.nix
  ./services/backup/borgbackup.nix
  ./services/backup/restic.nix
  ./services/desktops/accountsservice.nix
  ./services/desktops/ayatana-indicators.nix
  ./services/desktops/blueman.nix
  ./services/desktops/dunst.nix
  ./services/desktops/flatpak.nix
  ./services/desktops/geoclue2.nix
  ./services/desktops/gnome/gcr-ssh-agent.nix
  ./services/desktops/gnome/gnome-keyring.nix
  ./services/desktops/pipewire/pipewire.nix
  ./services/desktops/pipewire/wireplumber.nix
  ./services/desktops/profile-sync-daemon.nix
  ./services/desktops/seatd.nix
  ./services/desktops/system-config-printer.nix
  ./services/display-managers/default.nix
  ./services/display-managers/gdm.nix
  ./services/display-managers/generic.nix
  ./services/display-managers/greetd.nix
  ./services/display-managers/lemurs.nix
  ./services/display-managers/ly.nix
  ./services/display-managers/plasma-login-manager.nix
  ./services/display-managers/sddm.nix
  ./services/hardware/acpid.nix
  ./services/hardware/amdgpu.nix
  ./services/hardware/auto-cpufreq.nix
  ./services/hardware/bluetooth.nix
  ./services/hardware/bolt.nix
  ./services/hardware/fwupd.nix
  ./services/hardware/irqbalance.nix
  ./services/hardware/libinput.nix
  ./services/hardware/pcscd.nix
  ./services/hardware/power-profiles-daemon.nix
  ./services/hardware/ratbagd.nix
  ./services/hardware/sane.nix
  ./services/hardware/tlp.nix
  ./services/hardware/udev.nix
  ./services/hardware/udisks2.nix
  ./services/hardware/upower.nix
  ./services/hardware/usbmuxd.nix
  ./services/logging/logrotate.nix
  ./services/logging/rsyslogd.nix
  ./services/logging/syslog-ng.nix
  ./services/mail/mail.nix
  ./services/misc/devmon.nix
  ./services/misc/fstrim.nix
  ./services/misc/graphical-desktop.nix
  ./services/misc/nix-gc.nix
  ./services/misc/nix-optimise.nix
  ./services/misc/ollama.nix
  ./services/misc/persistent-evdev.nix
  ./services/misc/rsync.nix
  ./services/misc/safeeyes.nix
  ./services/misc/snapper.nix
  ./services/misc/sssd.nix
  ./services/monitoring/grafana.nix
  ./services/monitoring/loki.nix
  ./services/monitoring/netdata.nix
  ./services/monitoring/smartd.nix
  ./services/monitoring/sysstat.nix
  ./services/monitoring/vnstat.nix
  ./services/network-filesystems/samba.nix
  ./services/networking/adguardhome.nix
  ./services/networking/avahi-daemon.nix
  ./services/networking/bitcoind.nix
  ./services/networking/dhcpcd.nix
  ./services/networking/dnscrypt-proxy.nix
  ./services/networking/dnsmasq.nix
  ./services/networking/firewall.nix
  ./services/networking/firewalld
  ./services/networking/ghostunnel.nix
  ./services/networking/iwd.nix
  ./services/networking/modemmanager.nix
  ./services/networking/mosquitto.nix
  ./services/networking/mstpd.nix
  ./services/networking/nat.nix
  ./services/networking/networkmanager.nix
  ./services/networking/nftables.nix
  ./services/networking/ntp/chrony.nix
  ./services/networking/openvpn.nix
  ./services/networking/resilio.nix
  ./services/networking/rpcbind.nix
  ./services/networking/shairport-sync.nix
  ./services/networking/ssh/sshd.nix
  ./services/networking/syncthing.nix
  ./services/networking/tailscale.nix
  ./services/networking/unbound.nix
  ./services/networking/wireguard.nix
  ./services/networking/wpa_supplicant.nix
  ./services/printing/cupsd.nix
  ./services/scheduling/cron.nix
  ./services/security/fail2ban.nix
  ./services/security/fprintd.nix
  ./services/security/howdy
  ./services/security/intune.nix
  ./services/security/kanidm.nix
  ./services/security/tor.nix
  ./services/system/dbus.nix
  ./services/system/earlyoom.nix
  ./services/system/kerberos/default.nix
  ./services/system/nix-daemon-firewall.nix
  ./services/system/nix-daemon.nix
  ./services/system/nscd.nix
  ./services/system/systembus-notify.nix
  ./services/system/userborn.nix
  ./services/system/zram-generator.nix
  ./services/ttys/getty.nix
  ./services/video/v4l2-relayd.nix
  ./services/x11/colord.nix
  ./services/x11/display-managers/default.nix
  ./services/x11/display-managers/lightdm.nix
  ./services/x11/display-managers/startx.nix
  ./services/x11/display-managers/sx.nix
  ./services/x11/display-managers/xpra.nix
  ./services/x11/xscreensaver.nix
  ./services/x11/xserver.nix
  ./system/activation/activatable-system.nix
  ./system/activation/activation-script.nix
  ./system/activation/bootspec.nix
  ./system/activation/nixos-init.nix
  ./system/activation/pre-switch-check.nix
  ./system/activation/specialisation.nix
  ./system/activation/switchable-system.nix
  ./system/activation/top-level.nix
  ./system/boot/binfmt.nix
  ./system/boot/clevis-luks-askpass.nix
  ./system/boot/clevis.nix
  ./system/boot/emergency-mode.nix
  ./system/boot/extra-initrd.nix
  ./system/boot/grow-partition.nix
  ./system/boot/initrd-network.nix
  ./system/boot/initrd-openvpn.nix
  ./system/boot/initrd-ssh.nix
  ./system/boot/kernel.nix
  ./system/boot/kexec.nix
  ./system/boot/loader/efi.nix
  ./system/boot/loader/external/external.nix
  ./system/boot/loader/generations-dir/generations-dir.nix
  ./system/boot/loader/generic-extlinux-compatible
  ./system/boot/loader/grub/grub.nix
  ./system/boot/loader/grub/ipxe.nix
  ./system/boot/loader/grub/memtest.nix
  ./system/boot/loader/init-script/init-script.nix
  ./system/boot/loader/limine/limine.nix
  ./system/boot/loader/loader.nix
  ./system/boot/loader/refind/refind.nix
  ./system/boot/loader/systemd-boot/systemd-boot.nix
  ./system/boot/luksroot.nix
  ./system/boot/modprobe.nix
  ./system/boot/networkd.nix
  ./system/boot/nix-store-veritysetup.nix
  ./system/boot/plymouth-tpm2-totp.nix
  ./system/boot/plymouth.nix
  ./system/boot/resolved.nix
  ./system/boot/shutdown.nix
  ./system/boot/stage-1.nix
  ./system/boot/stage-2.nix
  ./system/boot/stratisroot.nix
  ./system/boot/systemd.nix
  ./system/boot/systemd/coredump.nix
  ./system/boot/systemd/dm-verity.nix
  ./system/boot/systemd/fido2.nix
  ./system/boot/systemd/homed.nix
  ./system/boot/systemd/initrd-secrets.nix
  ./system/boot/systemd/initrd.nix
  ./system/boot/systemd/journald-gateway.nix
  ./system/boot/systemd/journald-remote.nix
  ./system/boot/systemd/journald-upload.nix
  ./system/boot/systemd/journald.nix
  ./system/boot/systemd/logind.nix
  ./system/boot/systemd/nspawn.nix
  ./system/boot/systemd/oomd.nix
  ./system/boot/systemd/repart.nix
  ./system/boot/systemd/shutdown.nix
  ./system/boot/systemd/sysupdate.nix
  ./system/boot/systemd/sysusers.nix
  ./system/boot/systemd/tmpfiles.nix
  ./system/boot/systemd/tpm2.nix
  ./system/boot/systemd/user.nix
  ./system/boot/systemd/userdbd.nix
  ./system/boot/timesyncd.nix
  ./system/boot/tmp.nix
  ./system/boot/tzpfms.nix
  ./system/boot/uki.nix
  ./system/boot/unl0kr.nix
  ./system/boot/uvesafb.nix
  ./system/boot/zram-as-tmp.nix
  ./system/boot/zswap.nix
  ./system/etc/etc-activation.nix
  ./system/service/systemd/system.nix
  ./system/service/systemd/user.nix
  ./tasks/auto-upgrade.nix
  ./tasks/bcache.nix
  ./tasks/cpu-freq.nix
  ./tasks/encrypted-devices.nix
  ./tasks/filesystems.nix
  ./tasks/filesystems/btrfs.nix
  ./tasks/filesystems/exfat.nix
  ./tasks/filesystems/ext.nix
  ./tasks/filesystems/nfs.nix
  ./tasks/filesystems/vfat.nix
  ./tasks/filesystems/xfs.nix
  ./tasks/filesystems/zfs.nix
  ./tasks/lvm.nix
  ./tasks/network-interfaces-systemd.nix
  ./tasks/network-interfaces.nix
  ./tasks/swraid.nix
  ./virtualisation/container-config.nix
  ./virtualisation/containers.nix
  ./virtualisation/docker.nix
  ./virtualisation/hyperv-guest.nix
  ./virtualisation/libvirtd.nix
  ./virtualisation/lxc.nix
  ./virtualisation/nixos-containers.nix
  ./virtualisation/oci-containers.nix
  ./virtualisation/openvswitch.nix
  ./virtualisation/parallels-guest.nix
  ./virtualisation/podman/default.nix
  ./virtualisation/virtualbox-guest.nix
]
